name: Предложение
description: Предложить источник или улучшение
title: "feature: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какая задача решается
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Предлагаемое решение
    validations:
      required: true
